cache:
  directories:
  - .autoconf
  - $HOME/.m2
jobs:
  include:
    - language: java
      stage: Markdowner (Java)
      jdk:
        - openjdk11
      cache:
        directories:
        - .autoconf
        - $HOME/.m2
      install:
        - mvn dependency:resolve
      script:
        - mvn clean install coveralls:report -Dconsolerizer.show=false -DrepoToken=${COVERALLS_TOKEN}"
        - bash <(curl -s https://codecov.io/bash)
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java Kotlin $(find **/jacoco*.xml -printf '-r %p ')
