name: markdowner-pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Build and Test
        run:  mvn clean install jacoco:prepare-agent package jacoco:report