name: MD Pull Request
on:
  pull_request:
    branches: [ master ]
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: make b

      - name: Coverage
        run: make coverage
